### ISSUE TITLE
Squishing fails - No such file or directory

### ISSUE THREAD

**Issue by darxis** [control4/drivers-driverpackager#12]
Hi,

I am trying to build a simple Hello World driver with squishing enabled on Ubuntu 20.04.
I have the `squishy` file in the same dir as the `.c4zproj` file with the following content:
```
Main "driver.lua"

Output "driver.lua.squished"
```

My c4zproj file has the following content:
```
<Driver type="c4z" name="AppX" squishLua="true" encryption="true">
 <Items>
  <Item type="file" name="driver.lua" />
  <Item type="file" name="driver.xml" />
 </Items>
</Driver>
```

I am using the following command from within `dp3` dir to build the driver:
`./driverpackager.py ~/Documents/Repos/AppX ~/Documents/Repos/AppX -v`

However, it returns the following error:
```
CommandLine: 
luajit /home/userx/Documents/Repos/AppX/squish --no-minify /home/userx/Documents/Repos/AppX
luajit: cannot open /home/userx/Documents/Repos/AppX/squish: No such file or directory
```

I don't understand why everywhere in the docs or other repos it is written to create a file named `squishy` while based on the above error the driverpackager script tells luajit to use a file named `squish`, not `squishy`.
Also, I tried to rename my `squishy` file to `squish` but then it returns another error:
```
luajit: ...serx/Documents/Repos/AppX/squish:1: attempt to call global 'Main' (a nil value)
stack traceback:
	...owski/Documents/Repos/AppX/squish:1: in main chunk
	[C]: at 0x55e45a1ed1d0
```

So with either a `squish` or `squishy` file it does not work for me :( Can anyone tell me what am I doing wrong?

**Comment by WWalshC4** [comment]
`squish` is the name of the Lua script that squishes your files according to the content of the `squishy` file. It is in the `dp3` folder.
The way I have this setup is that the `dp3` folder is on my `PATH` so I can run `driverpackager.py` from the directory containing the `.c4zproj` file.
