### ISSUE TITLE
Install and Setup on Linux &/Or Windows

### ISSUE THREAD

**Issue by dinolink22** [control4/drivers-driverpackager#19]
I spent hours to try to understand how to do this but i'm simply not able to.

I have installed Python 3.10.3, have Lua 5.4 installed and I think M2Crypto is installed.

I can use the driverpackager.py all fine.
But the encrypt.py fails, it says:
"ModuleNotFoundError: No module named 'M2Crypto._m2crypto'"

Can somebody please make some kind of detailed instruction on how to install M2Crypto and all the requirements properly so this can be used or at least explain to me how to do it, on either one of the systems? 
I would prefer on windows bit linux is fine as well.
PLEASE! Thank you!

**Comment by WWalshC4** [comment]
Getting it working natively on Windows isn't something I can advise on as I've done all of this under Linux.  However, I have had good look doing the same steps in WSL (I have Ubuntu there).

The  [`Dockerfile`](https://github.com/control4/drivers-driverpackager/blob/master/Dockerfile) for this repo shows how to set up the environment on an Ubuntu install as that's what the GitHub Action uses that this repository exposes:

```
apt-get update
apt-get install -y build-essential
apt-get install -y python3-dev
apt-get install -y swig
apt-get install -y luajit
pip install m2crypto
```

**Comment by dinolink22** [comment]
Thank you for your answer. I am using Ubuntu.

I tried using the commands in the terminal but the last one was failing.
So I installed the Dockerfile script you mentioned with Docker and everything went well.

![image](https://user-images.githubusercontent.com/91555793/159586511-9f0650ba-dcbb-4f27-89be-ee13e012bd22.png)

if i run it you can see that it shows the -help for the driverpackager.py.
how do i use and edit the commands though? How do i add the srcdir dsrdir? also i want to only use the encrypt_c4z.py?
Thanks!

**Comment by WWalshC4** [comment]
I would not suggest running this in Docker locally, as then you will have to import/export your driver files.  The Dockerfile is there to support the GitHub Action published by this repo, and I provided it to show the list of dependencies.

If the `pip install m2crypto` is failing on your system, then you need to resolve that; M2Crypto is a dependency for encrypting drivers.  I am afraid that I cannot help with specific system queries as all environments are different.

**Comment by dinolink22** [comment]
@WWalshC4 We are making progress! :D 
So I finally managed to make it work, now m2crypto is installed and it works. So thanks!

I tried using the driverpackager.py and it creates the driver but it doesn't encrypt the driver?
if i encrypt it beforehand with the encrypt_c4z.py and then use the driverpackager the driver breaks, i mean even composer can't read the lua file. (the files are created successfully though)
Am i doing it wrong? 

Also i have no idea how to squish the files, tried reading the link in the README.md but... yeah... anyway so i squish them with driver editor to a driver.lua, it's just more steps but it's okay i guess?

Thanks!

**Comment by WWalshC4** [comment]
The `.c4proj file` and the `driver.xml` define these behaviors:

If the `.c4zproj` file that you're passing to DriverPackager has the `squishLua="true"` attribute in the `Driver` tag, then  DriverPackager will run the `squishy` file before adding any files to the generated driver.

If the `driver.xml` file has the `encryption="2"` attribute in the `script` tag, then DriverPackager will encrypt the driver.

**Comment by dinolink22** [comment]
@WWalshC4 Done! Perfect!! It's encrypted and it works! Thank you so much for your help!
